// <copyright file="Program.cs" company="PublicDomain.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

using System;
using System.Threading;
using System.Windows.Forms;

namespace PrintScreenToPaint
{
    /// <summary>
    /// Class with program entry point.
    /// </summary>
    internal sealed class Program
    {
        /// <summary>
        /// The mutex.
        /// </summary>
        private static Mutex ptpMutex;

        /// <summary>
        /// Program entry point.
        /// </summary>
        [STAThread]
        private static void Main(string[] args)
        {
            // Boolean flag for new instance
            bool newInstance;

            // Set mutex
            ptpMutex = new Mutex(true, @"Global\" + "PrintScreenToPaint", out newInstance);

            // Prevent it from being garbage-collected
            GC.KeepAlive(ptpMutex);

            // Check for former instance (if it's not new, it's an existing/previous one)
            if (!newInstance)
            {
                // Advise user
                MessageBox.Show("Only one instance of the program allowed.", "Previous instance detected", MessageBoxButtons.OK, MessageBoxIcon.Error);

                // Halt program
                return;
            }

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }

    }
}
